project_id = "zninjnjujptjxdikehun"

[functions.send-comment-verification]
verify_jwt = false

[functions.verify-comment]
verify_jwt = false

[functions.generate-article-fields]
verify_jwt = true

[functions.run-newsroom]
verify_jwt = true

[functions.newsroom-scheduled]
verify_jwt = false

[functions.rss-feed]
verify_jwt = false

[functions.manual-article-submit]
verify_jwt = true

[functions.auto-comment]
verify_jwt = false

[functions.extract-cities]
verify_jwt = false

[functions.send-newsletter-digest]
verify_jwt = false

[functions.auto-tweet]
verify_jwt = false

[functions.ingest-edhub]
verify_jwt = false

[functions.ingest-ghchronicles]
verify_jwt = false
